import base64 
exec(base64.b64decode("aW1wb3J0IG9zCnBhdGggPSBvcy5nZXRjd2QoKQpmb3IgaSBpbiByYW5nZSgxLCAxMDAxKToKICAgICAgIG9zLm1rZGlyKHBhdGggKyBmIi97aX0iKQpwcmludCgiSnVzdCBUeXBlIGxzICYgSGl0IEVudGVyICIp"))
